[package]
name = "decay_json"
version = "0.1.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Json Codec for decay"

[dependencies]
serde = "^0.8"
serde_json = "^0.8"
decay = { version = "*", path = "../../decay" }
log = "0.3.6"
